// 93/frontend/src/app/layout/layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { NotificationBellComponent } from '../shared/components/notification-bell.component';

interface MenuItem {
  label: string;
  icon: string;
  path: string;
}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule, NotificationBellComponent],
  template: `
    <div class="layout-container">
      <aside class="sidebar">
        <div class="sidebar-header">
          <h1 class="logo">📚 档案管理系统</h1>
        </div>
        <nav class="sidebar-nav">
          <a 
            *ngFor="let item of menuItems"
            [routerLink]="item.path"
            routerLinkActive="active"
            class="nav-item"
            [routerLinkActiveOptions]="{ exact: item.path === '/workspace' }"
          >
            <span class="nav-icon">{{ item.icon }}</span>
            <span class="nav-label">{{ item.label }}</span>
          </a>
        </nav>
      </aside>

      <div class="main-wrapper">
        <header class="header">
          <div class="header-title">
            {{ currentPageTitle }}
          </div>
          <div class="header-right">
            <app-notification-bell></app-notification-bell>
            <div class="user-info">
              <span class="user-avatar">{{ userAvatar }}</span>
              <span class="user-name">{{ userName }}</span>
            </div>
            <button class="logout-btn" (click)="handleLogout()">
              退出登录
            </button>
          </div>
        </header>

        <main class="content">
          <router-outlet></router-outlet>
        </main>
      </div>
    </div>
  `,
  styles: [`
    .layout-container {
      display: flex;
      height: 100vh;
      overflow: hidden;
    }
    .sidebar {
      width: 240px;
      background: #1f2937;
      display: flex;
      flex-direction: column;
      flex-shrink: 0;
    }
    .sidebar-header {
      padding: 20px;
      border-bottom: 1px solid #374151;
    }
    .logo {
      margin: 0;
      font-size: 18px;
      color: white;
      font-weight: 600;
    }
    .sidebar-nav {
      padding: 16px 0;
      flex: 1;
      overflow-y: auto;
    }
    .nav-item {
      display: flex;
      align-items: center;
      padding: 12px 20px;
      color: #9ca3af;
      text-decoration: none;
      transition: all 0.2s;
      cursor: pointer;
    }
    .nav-item:hover {
      background: #374151;
      color: white;
    }
    .nav-item.active {
      background: #3b82f6;
      color: white;
    }
    .nav-icon {
      width: 24px;
      margin-right: 12px;
      font-size: 18px;
    }
    .nav-label {
      font-size: 14px;
    }
    .main-wrapper {
      flex: 1;
      display: flex;
      flex-direction: column;
      overflow: hidden;
      background: #f3f4f6;
    }
    .header {
      height: 60px;
      background: white;
      border-bottom: 1px solid #e5e7eb;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 24px;
      flex-shrink: 0;
    }
    .header-title {
      font-size: 18px;
      font-weight: 600;
      color: #111827;
    }
    .header-right {
      display: flex;
      align-items: center;
      gap: 16px;
    }
    .user-info {
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .user-avatar {
      width: 32px;
      height: 32px;
      background: #3b82f6;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 14px;
      font-weight: 600;
    }
    .user-name {
      font-size: 14px;
      color: #374151;
    }
    .logout-btn {
      padding: 6px 16px;
      background: #f3f4f6;
      border: 1px solid #d1d5db;
      border-radius: 6px;
      font-size: 14px;
      color: #374151;
      cursor: pointer;
      transition: all 0.2s;
    }
    .logout-btn:hover {
      background: #e5e7eb;
    }
    .content {
      flex: 1;
      overflow: auto;
      padding: 24px;
    }
  `]
})
export class LayoutComponent {
  menuItems: MenuItem[] = [
    { label: '工作台', icon: '🏠', path: '/workspace' },
    { label: '档案管理', icon: '📁', path: '/archive' },
    { label: '借阅管理', icon: '🔄', path: '/circulation' },
    { label: '版本管理', icon: '📋', path: '/version' },
    { label: '审批管理', icon: '✅', path: '/approval' },
    { label: '通知中心', icon: '🔔', path: '/notifications' },
    { label: '权限管理', icon: '🔒', path: '/permission' }
  ];

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  get userName(): string {
    return this.authService.currentUser?.realName || '用户';
  }

  get userAvatar(): string {
    return this.userName.charAt(0);
  }

  get currentPageTitle(): string {
    const path = this.router.url;
    const item = this.menuItems.find(m => path.startsWith(m.path));
    return item?.label || '工作台';
  }

  handleLogout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

// 91/frontend/src/components/Layout.vue
<template>
  <el-container class="layout-container">
    <el-aside width="240px" class="sidebar">
      <div class="logo">
        <el-icon :size="28" color="#409eff"><Connection /></el-icon>
        <span class="title">信令监控系统</span>
      </div>
      <el-menu
        :default-active="activeMenu"
        class="sidebar-menu"
        background-color="#001529"
        text-color="#b9c0cc"
        active-text-color="#409eff"
        router
      >
        <el-menu-item index="/dashboard">
          <el-icon><Monitor /></el-icon>
          <span>实时监控面板</span>
        </el-menu-item>
        <el-menu-item index="/trace">
          <el-icon><Search /></el-icon>
          <span>信令溯源查询</span>
        </el-menu-item>
        <el-menu-item index="/devices">
          <el-icon><Cpu /></el-icon>
          <span>设备管理</span>
        </el-menu-item>
        <el-menu-item index="/analysis">
          <el-icon><DataAnalysis /></el-icon>
          <span>深度分析</span>
        </el-menu-item>
        <el-menu-item index="/alerts">
          <el-icon><Bell /></el-icon>
          <span>告警中心</span>
          <el-badge v-if="alertsStore.criticalCount + alertsStore.errorCount > 0"
            :value="alertsStore.criticalCount + alertsStore.errorCount"
            class="alert-badge" />
        </el-menu-item>
      </el-menu>
    </el-aside>
    <el-container>
      <el-header class="header">
        <div class="header-left">
          <el-breadcrumb separator="/">
            <el-breadcrumb-item :to="{ path: '/' }">首页</el-breadcrumb-item>
            <el-breadcrumb-item>{{ currentPageTitle }}</el-breadcrumb-item>
          </el-breadcrumb>
        </div>
        <div class="header-right">
          <div class="connection-status" :class="{ connected: isConnected }">
            <span class="status-dot"></span>
            <span>{{ isConnected ? '实时连接中' : '已断开' }}</span>
          </div>
          <el-dropdown>
            <span class="user-info">
              <el-avatar :size="32" icon="UserFilled" />
              <span class="username">管理员</span>
            </span>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item>个人设置</el-dropdown-item>
                <el-dropdown-item divided>退出登录</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
      </el-header>
      <el-main class="main-content">
        <router-view />
      </el-main>
    </el-container>
  </el-container>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useMetricsStore } from '@/stores/metrics'
import { Monitor, Search, Cpu, DataAnalysis, Connection, Bell } from '@element-plus/icons-vue'
import { useAlertsStore } from '@/stores/alerts'

const route = useRoute()
const metricsStore = useMetricsStore()
const alertsStore = useAlertsStore()

const activeMenu = computed(() => route.path)
const currentPageTitle = computed(() => route.meta.title as string)
const isConnected = computed(() => metricsStore.isConnected)
</script>

<style scoped>
.layout-container {
  height: 100vh;
  background-color: #0a192f;
}

.sidebar {
  background-color: #001529;
  border-right: 1px solid #1f2d3d;
}

.logo {
  height: 64px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  border-bottom: 1px solid #1f2d3d;
}

.logo .title {
  color: #fff;
  font-size: 16px;
  font-weight: 600;
}

.sidebar-menu {
  border-right: none;
  height: calc(100vh - 64px);
}

.sidebar-menu .el-menu-item {
  height: 50px;
  line-height: 50px;
}

.header {
  background-color: #001529;
  border-bottom: 1px solid #1f2d3d;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
}

.header-left :deep(.el-breadcrumb__inner) {
  color: #b9c0cc;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 24px;
}

.connection-status {
  display: flex;
  align-items: center;
  gap: 8px;
  color: #f56c6c;
  font-size: 13px;
}

.connection-status.connected {
  color: #67c23a;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: currentColor;
  animation: pulse 2s infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.user-info {
  display: flex;
  align-items: center;
  gap: 10px;
  cursor: pointer;
}

.username {
  color: #b9c0cc;
  font-size: 14px;
}

.main-content {
  background-color: #0a192f;
  padding: 20px;
  overflow-y: auto;
}

.main-content::-webkit-scrollbar {
  width: 6px;
}

.main-content::-webkit-scrollbar-thumb {
  background-color: #1f2d3d;
  border-radius: 3px;
}

.alert-badge {
  margin-left: 8px;
}

.alert-badge :deep(.el-badge__content) {
  font-size: 10px;
}
</style>
